name: test-build

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    tags:
      - '!*'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.x

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install tools
        run: make install-tools

      - name: Cache for go pkg
        uses: actions/cache@v2
        with:
          path: ~/go/pkg
          key: ${{ runner.os }}-go-cache-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-cache-

      - name: Cache for go-build
        uses: actions/cache@v2
        with:
          path: ~/.cache/go-build
          key: ${{ runner.os }}-go-build-cache-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-build-cache-

      - name: Test
        run: make test
        env:
          RICHGO_FORCE_COLOR: 1

      - name: Build
        run: make build
